name : Outputs
on:
  workflow_dispatch:
jobs:
  output_job:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"