name: Timestamp
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  timestamp_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get current timestamp
        run: echo "Current timestamp: $(date)"